[project]
name = "mlflow-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.6",
    "langchain-text-splitters>=0.3.0",
    "pypdf>=6.5.0",
    "chromadb>=0.4.0",
    "python-dotenv>=1.0.0",
    "langchain-chroma>=1.1.0",
    "langchain>=1.2.0",
    "mlflow>=3.8.1",
    "openai>=2.14.0",
    "deepeval>=3.7.7",
    "litellm>=1.0.0",
    "dotenv>=0.9.9",
]
